### PR TITLE
improved indentation #3

### PR DESCRIPTION
**Pull request by fab1an**
This further improves indentation when used with JSX and adds the special behaviour of braces after switch statements.

### CODE REVIEW

**Review by ravasthi — APPROVED** [review]
I tried this locally and JSX still doesn't indent properly, but again, it's not worse than before, so it's okay to merge.

**Comment by fab1an** [comment]
@ravasthi Could you not give me a short obfuscated sample along with the desired output, so I can fix it for you?

**Comment by ravasthi** [comment]
@fab1an I put together a gist, and then realized that we may have been talking at cross-purposes here. I'll be the first to admit I don't understand `increaseIndentPattern` well, but I believe what you're talking about is when you're writing the code and you want TM to auto-indent to the right spot on  the next line when you hit return, like so:

``` jsx
{/* with an indent of 2 spaces */}
<span className="blah">
  {/* <- Expect indent preferences to put you at the spot where '{' is */}
```

However, when I hit return after the opening tag, the cursor was placed at the same column as the previous line for me.

What I was talking about was using the Indent Selection (`cmd + opt + [`) command on an [incorrectly-indented piece of code](https://gist.github.com/ravasthi/561dfa9ada674552fbce3e443259bab2). You can see samples of the starting state, the desired ending state, and the actual ending state.

**Comment by fab1an** [comment]
@ravasthi That is very weird, when I take your code from the gist, either the "actual" or the "incorrent" indentation and press Cmd+A to select all and then `cmd + opt + [` I get the correct indentation.

screen shot 2016-10-09 at 19 08 05

screen shot 2016-10-09 at 19 08 11

**Pull request merged**
